name: test

on: [push, pull_request]

jobs:
  node-lint-tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: init
      run:
        yarn install --frozen-lockfile

    - name: bundle test
      run:
        npx react-native bundle --entry-file index.js --bundle-output /dev/null

